# Kotlin
kotlin.code.style=official
kotlin.incremental=false
kotlin.daemon.jvm.options=-Xmx2g

# Gradle
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.configureondemand=false
org.gradle.warning.mode=none

# Android & Others
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.native.ignoreDisabledTargets=true
