org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=512m -Djava.io.tmpdir=/tmp -Duser.home=/tmp -XX:+UseSerialGC
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.vfs.watch=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
