# Forzar uso del JDK del sistema (Java 11 en Vercel)
org.gradle.java.home.auto-provisioning=false
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC
kotlin.compiler.execution.strategy=in-process
org.gradle.vfs.watch=false
org.gradle.warning.mode=none

# Kotlin
kotlin.incremental=false
kotlin.daemon.jvm.options=-Xmx1024m
# Se elimina kotlin.build.report.output=none porque causa error en Kotlin 2.1.0

# Android & Others
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.native.ignoreDisabledTargets=true
